// Praticas-Framework/vue-app-02/src/App.vue
<template>
  <Nav :setPagina="setPagina" />

  <Clipping v-if="pagina === 'blog'" />
  <Descricao v-if="pagina === 'descricao'" />
</template>

<script setup>
import { ref } from "vue";

import Nav from "@/components/Nav.vue";
import Descricao from "@/components/Descricao.vue";
import Clipping from "@/components/Clipping.vue";

const pagina = ref("blog");

function setPagina(valor) {
  pagina.value = valor;
}
</script>

// Praticas-Framework/react-app-02/src/App.jsx
import { useState } from "react";
import Nav from "./components/Nav";
import Descricao from "./components/Descricao";
import Clipping from "./components/Clipping";

export default function App() {
  const [pagina, setPagina] = useState("blog");

  return (
    <>
      <Nav setPagina={setPagina} />

      {pagina === "blog" && <Clipping />}
      {pagina === "descricao" && <Descricao />}
    </>
  );
}
